using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using NPTP.InputSystemWrapper.Utilities.Extensions;
using NPTP.InputSystemWrapper.Data;
using NPTP.InputSystemWrapper.Editor.Utilities;
using UnityEngine.InputSystem;

namespace NPTP.InputSystemWrapper.Editor
{
    internal static class Helper
    {
        private const string MARKER = "// MARKER";
        private const string START = "Start";
        private const string END = "End";

        // Assets
        internal static OfflineInputData OfflineInputData =>
            Generation.ProjectAssets.TryFindProjectAsset(nameof(OfflineInputData), out OfflineInputData offlineInputData) ? offlineInputData : null;
        
        // Template paths
        internal static string ActionsTemplateFileSystemPath => EditorAssetGetter.GetSystemFilePath(OfflineInputData.ActionsTemplateFile);
        
        private static char Sep => Path.DirectorySeparatorChar;
        
        // String extensions for code generation
        internal static string AsField(this string s) => s.AlphaNumericCharactersOnly().RemoveFirstCharacterIfNumber().AllWhitespaceTrimmed().LowercaseFirst();
        internal static string AsProperty(this string s) => s.AllWhitespaceTrimmed().CapitalizeFirst();
        internal static string AsType(this string s) => s.AllWhitespaceTrimmed().CapitalizeFirst();
        internal static string AsEnumMember(this string s) => s.AlphaNumericCharactersOnly().RemoveFirstCharacterIfNumber();
        internal static string AsInspectorLabel(this string s) => s.SpaceBetweenWords().CapitalizeFirst();
        
        /// <summary>
        /// Delete previously generated scripts without touching the assembly definition or anything else
        /// the user may have placed in the generated folder.
        /// </summary>
        internal static void ClearGeneratedScripts(string folderSystemPath)
        {
            if (!Directory.Exists(folderSystemPath))
            {
                Directory.CreateDirectory(folderSystemPath);
                return;
            }

            foreach (string filePath in Directory.GetFiles(folderSystemPath, "*.cs"))
            {
                File.Delete(filePath);
                if (File.Exists(filePath + ".meta")) File.Delete(filePath + ".meta");
            }
        }

        internal static void WriteLinesToFile(List<string> newLines, string filePath)
        {
            try
            {
                int sepIndex = filePath.LastIndexOf(Path.DirectorySeparatorChar);
                if (sepIndex >= 0)
                {
                    string directoryPath = filePath.Remove(sepIndex);
                    if (!Directory.Exists(directoryPath))
                    {
                        Directory.CreateDirectory(directoryPath);
                    }
                }

                using (StreamWriter sw = new(filePath))
                {
                    foreach (string line in newLines)
                    {
                        sw.WriteLine(line);
                    }
                }

                ISWDebug.Log($"{filePath} written successfully!");
            }
            catch (Exception e)
            {
                ISWDebug.Log($"File could not be written: {e.Message}");
            }
        }

        internal static List<string> GetGeneratorNoticeLines()
        {
            return new List<string>
            {
                $"// ------------------------------------------------------------------------------------------",
                $"// This file was automatically generated by {nameof(InputScriptGenerator)}. Do not modify it manually.",
                $"// ------------------------------------------------------------------------------------------"
            };
        }

        internal static IEnumerable<string> GetMapNames(InputActionAsset asset)
        {
            return asset.actionMaps.Select(map => map.name);
        }
        
        internal static bool IsMarkerStart(string line, out string markerName)
        {
            string trimmedLine = line.Trim();
            bool isMarkerStart = trimmedLine.StartsWith(MARKER) && trimmedLine.EndsWith(START);

            if (!isMarkerStart)
            {
                markerName = string.Empty;
                return false;
            }
            
            StringBuilder sb = new();
            int periodCount = 0;
            foreach (char c in trimmedLine)
            {
                if (c == '.')
                {
                    periodCount++;
                    if (periodCount == 2)
                    {
                        break;
                    }
                    continue;
                }

                if (periodCount == 1)
                {
                    sb.Append(c);
                }
            }

            markerName = sb.ToString();
            return true;
        }

        internal static bool IsMarkerEnd(string line)
        {
            string trimmedLine = line.Trim();
            return trimmedLine.StartsWith(MARKER) && trimmedLine.EndsWith(END);
        }
        
    }
}