using System.Collections.Generic;
using System.Linq;
using NPTP.InputSystemWrapper.Data;
using NPTP.UnitySourceGen.Editor.Syntax;
using UnityEngine.InputSystem;

namespace NPTP.InputSystemWrapper.Editor
{
    internal static class Helper
    {
        internal static OfflineInputData OfflineInputData =>
            Generation.ProjectAssets.TryFindProjectAsset(nameof(OfflineInputData), out OfflineInputData offlineInputData) ? offlineInputData : null;

        /// <summary>
        /// A PascalCase identifier, for a generated type or property. Sanitizing is left to the source gen
        /// package, which does it for every name it is given anyway; only the casing is ours to decide.
        /// </summary>
        internal static string AsType(this string s) => Capitalized(GeneratedIdentifier.Sanitize(s));

        /// <inheritdoc cref="AsType"/>
        internal static string AsProperty(this string s) => AsType(s);

        private static string Capitalized(string identifier)
        {
            return string.IsNullOrEmpty(identifier) || char.IsUpper(identifier[0])
                ? identifier
                : char.ToUpperInvariant(identifier[0]) + identifier.Substring(1);
        }

        internal static List<string> GetGeneratorNoticeLines()
        {
            return new List<string>
            {
                "// ------------------------------------------------------------------------------------------",
                $"// This file was automatically generated by {nameof(InputScriptGenerator)}. Do not modify it manually.",
                "// ------------------------------------------------------------------------------------------"
            };
        }

        internal static IEnumerable<string> GetMapNames(InputActionAsset asset)
        {
            return asset.actionMaps.Select(map => map.name);
        }
    }
}
